# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language set in hugo.yaml
en:
  languageName: English
  languageCode: en-us
  contentDir: content # different way: move English content into `content/en` sub-folder and copy content-folder into this subdir, then translate *everything*
  title: CompPhil²MMAE
#  weight: 1
#  taxonomies:
#    tag: tags
  # params:
  #  description: Site description in Chinese...
  # menu:
  #   main:
  #     - name: 传
  #       url: '#about'
  #       weight: 1

de:
  languageName: Deutsch
  languageCode: de
  contentDir: content
  title: CompPhil²MMAE
#  weight: 2
#  taxonomies:
#    tag: tags
