# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
de:
  languageCode: de
  contentDir: content/de

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en # »» copy content-folder to this place, then translate *everything*
  title: CompPhil²MMAE # PhilMMAE 
  # params:
  #  description: Site description in Chinese...
  # menu:
  #   main:
  #     - name: 传
  #       url: '#about'
  #       weight: 1
